// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testforproject.Data;

#nullable disable

namespace testforproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228122729_AddCategoryImages")]
    partial class AddCategoryImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryEvent", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("EventsEid")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "EventsEid");

                    b.HasIndex("EventsEid");

                    b.ToTable("EventCategories", (string)null);
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<int>("ParticitpantUid")
                        .HasColumnType("int");

                    b.HasKey("Eid", "ParticitpantUid");

                    b.HasIndex("ParticitpantUid");

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<int>("FollowerUid")
                        .HasColumnType("int");

                    b.Property<int>("FollowingUid")
                        .HasColumnType("int");

                    b.HasKey("FollowerUid", "FollowingUid");

                    b.HasIndex("FollowingUid");

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("testforproject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sports & Fitness"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.google.com/imgres?q=Gaming%20%26%20eSports&imgurl=https%3A%2F%2Fluhisummercamps.org%2Fwp-content%2Fuploads%2F2023%2F07%2Fheader-esports.jpg&imgrefurl=https%3A%2F%2Fluhisummercamps.org%2Fthe-benefits-of-competitive-gaming-and-esports%2F&docid=Wpg71i9teQo2KM&tbnid=MnZ1L84ExUZNGM&vet=12ahUKEwj4q-PxlvySAxV_iKgCHRQzA3AQnPAOegQIGRAB..i&w=1400&h=933&hcb=2&ved=2ahUKEwj4q-PxlvySAxV_iKgCHRQzA3AQnPAOegQIGRAB",
                            Name = "Gaming & eSports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance & Investing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technology & Coding"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Education & Learning"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Arts & Crafts"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Food & Drink"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Travel & Outdoors"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Networking & Business"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Music & Concerts"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Movies & Theater"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Photography & Video"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Books & Writing"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Language & Culture"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Volunteering & Charity"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pets & Animals"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Fashion & Beauty"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Science & Research"
                        },
                        new
                        {
                            Id = 20,
                            Name = "History & Philosophy"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Parenting & Family"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Spirituality & Beliefs"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cars & Motorcycles"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Real Estate"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Career Development"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Politics & Society"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Dancing & Performing"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Board Games & Tabletop"
                        },
                        new
                        {
                            Id = 29,
                            Name = "DIY & Home Improvement"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Comedy & Improv"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Environment & Nature"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Dating & Singles"
                        });
                });

            modelBuilder.Entity("testforproject.Models.Event", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Eid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStop")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ExpiredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticitpant")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eid");

                    b.HasIndex("OwnerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("testforproject.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserUid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserUid");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("testforproject.Models.Requirements", b =>
                {
                    b.Property<int>("RequirementsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementsId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantScore")
                        .HasColumnType("int");

                    b.HasKey("RequirementsId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("testforproject.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<long?>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HostScore")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipateScore")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryEvent", b =>
                {
                    b.HasOne("testforproject.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsEid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("testforproject.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("Eid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticitpantUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FollowerUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FollowingUid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("testforproject.Models.Event", b =>
                {
                    b.HasOne("testforproject.Models.User", "Owner")
                        .WithMany("OwningEvent")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("testforproject.Models.Notification", b =>
                {
                    b.HasOne("testforproject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("testforproject.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OwningEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
