// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testforproject.Data;

#nullable disable

namespace testforproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304124743_google")]
    partial class google
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryEvent", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("EventsEid")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "EventsEid");

                    b.HasIndex("EventsEid");

                    b.ToTable("EventCategories", (string)null);
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<int>("ParticitpantUid")
                        .HasColumnType("int");

                    b.HasKey("Eid", "ParticitpantUid");

                    b.HasIndex("ParticitpantUid");

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<int>("FollowerUid")
                        .HasColumnType("int");

                    b.Property<int>("FollowingUid")
                        .HasColumnType("int");

                    b.HasKey("FollowerUid", "FollowingUid");

                    b.HasIndex("FollowingUid");

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("testforproject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PC Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Console Gaming"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tabletop RPG"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cafe Hopping"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Movie Night"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Karaoke"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Escape Room"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Theme Park"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Badminton"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bowling"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gym & Fitness"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Street Food"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fine Dining"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pub Crawl"
                        },
                        new
                        {
                            Id = 21,
                            Name = "BBQ / Grill"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Concert & Live Music"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Museum / Art Gallery"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Road Trip"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Spa Day"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cooking Class"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hackathon / Coding"
                        });
                });

            modelBuilder.Entity("testforproject.Models.Event", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Eid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStop")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("ExpiredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticitpant")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eid");

                    b.HasIndex("OwnerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("testforproject.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserUid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserUid");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("testforproject.Models.Requirements", b =>
                {
                    b.Property<int>("RequirementsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementsId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParticipantScore")
                        .HasColumnType("int");

                    b.HasKey("RequirementsId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("testforproject.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<long?>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HostScore")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipateScore")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryEvent", b =>
                {
                    b.HasOne("testforproject.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsEid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("testforproject.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("Eid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticitpantUid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FollowerUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testforproject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FollowingUid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("testforproject.Models.Event", b =>
                {
                    b.HasOne("testforproject.Models.User", "Owner")
                        .WithMany("OwningEvent")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("testforproject.Models.Notification", b =>
                {
                    b.HasOne("testforproject.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("testforproject.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OwningEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
